//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIN_InvoiceEDI.KIN_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="INUPUT_DATA", Namespace="http://Kmieai/DMDI/data")]
    [System.SerializableAttribute()]
    public partial class INUPUT_DATA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KIN_InvoiceEDI.KIN_Service.TAB_DATA_HEADER[] GET_DATAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public KIN_InvoiceEDI.KIN_Service.TAB_DATA_HEADER[] GET_DATA {
            get {
                return this.GET_DATAField;
            }
            set {
                if ((object.ReferenceEquals(this.GET_DATAField, value) != true)) {
                    this.GET_DATAField = value;
                    this.RaisePropertyChanged("GET_DATA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TAB_DATA_HEADER", Namespace="http://Kmieai/DMDI/data")]
    [System.SerializableAttribute()]
    public partial class TAB_DATA_HEADER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVDATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIFNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZSHOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBELNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVQTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZAIVAMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZANETPRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZANETWRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZCGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZSGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZUGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZATCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZHSNSACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZGSTINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEHNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EWAYBILLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNUM1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNUM2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNUM3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNUM4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNUM5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZCHAR2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZCHAR3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZCHAR4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZCHAR5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IVNUM {
            get {
                return this.IVNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.IVNUMField, value) != true)) {
                    this.IVNUMField = value;
                    this.RaisePropertyChanged("IVNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IVDAT {
            get {
                return this.IVDATField;
            }
            set {
                if ((object.ReferenceEquals(this.IVDATField, value) != true)) {
                    this.IVDATField = value;
                    this.RaisePropertyChanged("IVDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LIFNR {
            get {
                return this.LIFNRField;
            }
            set {
                if ((object.ReferenceEquals(this.LIFNRField, value) != true)) {
                    this.LIFNRField = value;
                    this.RaisePropertyChanged("LIFNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MATNR {
            get {
                return this.MATNRField;
            }
            set {
                if ((object.ReferenceEquals(this.MATNRField, value) != true)) {
                    this.MATNRField = value;
                    this.RaisePropertyChanged("MATNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZSHOP {
            get {
                return this.ZSHOPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZSHOPField, value) != true)) {
                    this.ZSHOPField = value;
                    this.RaisePropertyChanged("ZSHOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EBELN {
            get {
                return this.EBELNField;
            }
            set {
                if ((object.ReferenceEquals(this.EBELNField, value) != true)) {
                    this.EBELNField = value;
                    this.RaisePropertyChanged("EBELN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IVQTY {
            get {
                return this.IVQTYField;
            }
            set {
                if ((object.ReferenceEquals(this.IVQTYField, value) != true)) {
                    this.IVQTYField = value;
                    this.RaisePropertyChanged("IVQTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ZAIVAMT {
            get {
                return this.ZAIVAMTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZAIVAMTField, value) != true)) {
                    this.ZAIVAMTField = value;
                    this.RaisePropertyChanged("ZAIVAMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ZANETPR {
            get {
                return this.ZANETPRField;
            }
            set {
                if ((object.ReferenceEquals(this.ZANETPRField, value) != true)) {
                    this.ZANETPRField = value;
                    this.RaisePropertyChanged("ZANETPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ZANETWR {
            get {
                return this.ZANETWRField;
            }
            set {
                if ((object.ReferenceEquals(this.ZANETWRField, value) != true)) {
                    this.ZANETWRField = value;
                    this.RaisePropertyChanged("ZANETWR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ZCGST {
            get {
                return this.ZCGSTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZCGSTField, value) != true)) {
                    this.ZCGSTField = value;
                    this.RaisePropertyChanged("ZCGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ZSGST {
            get {
                return this.ZSGSTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZSGSTField, value) != true)) {
                    this.ZSGSTField = value;
                    this.RaisePropertyChanged("ZSGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ZIGST {
            get {
                return this.ZIGSTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIGSTField, value) != true)) {
                    this.ZIGSTField = value;
                    this.RaisePropertyChanged("ZIGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ZUGST {
            get {
                return this.ZUGSTField;
            }
            set {
                if ((object.ReferenceEquals(this.ZUGSTField, value) != true)) {
                    this.ZUGSTField = value;
                    this.RaisePropertyChanged("ZUGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ZATCS {
            get {
                return this.ZATCSField;
            }
            set {
                if ((object.ReferenceEquals(this.ZATCSField, value) != true)) {
                    this.ZATCSField = value;
                    this.RaisePropertyChanged("ZATCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ZHSNSAC {
            get {
                return this.ZHSNSACField;
            }
            set {
                if ((object.ReferenceEquals(this.ZHSNSACField, value) != true)) {
                    this.ZHSNSACField = value;
                    this.RaisePropertyChanged("ZHSNSAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ZGSTIN {
            get {
                return this.ZGSTINField;
            }
            set {
                if ((object.ReferenceEquals(this.ZGSTINField, value) != true)) {
                    this.ZGSTINField = value;
                    this.RaisePropertyChanged("ZGSTIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string VEHNO {
            get {
                return this.VEHNOField;
            }
            set {
                if ((object.ReferenceEquals(this.VEHNOField, value) != true)) {
                    this.VEHNOField = value;
                    this.RaisePropertyChanged("VEHNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string IRN {
            get {
                return this.IRNField;
            }
            set {
                if ((object.ReferenceEquals(this.IRNField, value) != true)) {
                    this.IRNField = value;
                    this.RaisePropertyChanged("IRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string EWAYBILL {
            get {
                return this.EWAYBILLField;
            }
            set {
                if ((object.ReferenceEquals(this.EWAYBILLField, value) != true)) {
                    this.EWAYBILLField = value;
                    this.RaisePropertyChanged("EWAYBILL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ZNUM1 {
            get {
                return this.ZNUM1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZNUM1Field, value) != true)) {
                    this.ZNUM1Field = value;
                    this.RaisePropertyChanged("ZNUM1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string ZNUM2 {
            get {
                return this.ZNUM2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZNUM2Field, value) != true)) {
                    this.ZNUM2Field = value;
                    this.RaisePropertyChanged("ZNUM2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string ZNUM3 {
            get {
                return this.ZNUM3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZNUM3Field, value) != true)) {
                    this.ZNUM3Field = value;
                    this.RaisePropertyChanged("ZNUM3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ZNUM4 {
            get {
                return this.ZNUM4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZNUM4Field, value) != true)) {
                    this.ZNUM4Field = value;
                    this.RaisePropertyChanged("ZNUM4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ZNUM5 {
            get {
                return this.ZNUM5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZNUM5Field, value) != true)) {
                    this.ZNUM5Field = value;
                    this.RaisePropertyChanged("ZNUM5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ZCHAR2 {
            get {
                return this.ZCHAR2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCHAR2Field, value) != true)) {
                    this.ZCHAR2Field = value;
                    this.RaisePropertyChanged("ZCHAR2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string ZCHAR3 {
            get {
                return this.ZCHAR3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCHAR3Field, value) != true)) {
                    this.ZCHAR3Field = value;
                    this.RaisePropertyChanged("ZCHAR3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ZCHAR4 {
            get {
                return this.ZCHAR4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCHAR4Field, value) != true)) {
                    this.ZCHAR4Field = value;
                    this.RaisePropertyChanged("ZCHAR4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string ZCHAR5 {
            get {
                return this.ZCHAR5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCHAR5Field, value) != true)) {
                    this.ZCHAR5Field = value;
                    this.RaisePropertyChanged("ZCHAR5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DATA", Namespace="http://Kmieai/DMDI/data")]
    [System.SerializableAttribute()]
    public partial class O_DATA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KIN_InvoiceEDI.KIN_Service.TAB_DATA[] GET_DATA_01Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public KIN_InvoiceEDI.KIN_Service.TAB_DATA[] GET_DATA_01 {
            get {
                return this.GET_DATA_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.GET_DATA_01Field, value) != true)) {
                    this.GET_DATA_01Field = value;
                    this.RaisePropertyChanged("GET_DATA_01");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TAB_DATA", Namespace="http://Kmieai/DMDI/data")]
    [System.SerializableAttribute()]
    public partial class TAB_DATA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVDATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIFNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IFFAILMSGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IFRESULTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IVNUM {
            get {
                return this.IVNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.IVNUMField, value) != true)) {
                    this.IVNUMField = value;
                    this.RaisePropertyChanged("IVNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IVDAT {
            get {
                return this.IVDATField;
            }
            set {
                if ((object.ReferenceEquals(this.IVDATField, value) != true)) {
                    this.IVDATField = value;
                    this.RaisePropertyChanged("IVDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LIFNR {
            get {
                return this.LIFNRField;
            }
            set {
                if ((object.ReferenceEquals(this.LIFNRField, value) != true)) {
                    this.LIFNRField = value;
                    this.RaisePropertyChanged("LIFNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IFFAILMSG {
            get {
                return this.IFFAILMSGField;
            }
            set {
                if ((object.ReferenceEquals(this.IFFAILMSGField, value) != true)) {
                    this.IFFAILMSGField = value;
                    this.RaisePropertyChanged("IFFAILMSG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IFRESULT {
            get {
                return this.IFRESULTField;
            }
            set {
                if ((object.ReferenceEquals(this.IFRESULTField, value) != true)) {
                    this.IFRESULTField = value;
                    this.RaisePropertyChanged("IFRESULT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Kmieai/DMDI/data", ConfigurationName="KIN_Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HEXADECIMAL from namespace http://Kmieai/DMDI/data is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Kmieai/DMDI/data/getData", ReplyAction="*")]
        KIN_InvoiceEDI.KIN_Service.getDataResponse getData(KIN_InvoiceEDI.KIN_Service.getDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kmieai/DMDI/data/getData", ReplyAction="*")]
        System.Threading.Tasks.Task<KIN_InvoiceEDI.KIN_Service.getDataResponse> getDataAsync(KIN_InvoiceEDI.KIN_Service.getDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getData", Namespace="http://Kmieai/DMDI/data", Order=0)]
        public KIN_InvoiceEDI.KIN_Service.getDataRequestBody Body;
        
        public getDataRequest() {
        }
        
        public getDataRequest(KIN_InvoiceEDI.KIN_Service.getDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class getDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HEXADECIMAL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public KIN_InvoiceEDI.KIN_Service.INUPUT_DATA data01;
        
        public getDataRequestBody() {
        }
        
        public getDataRequestBody(string HEXADECIMAL, KIN_InvoiceEDI.KIN_Service.INUPUT_DATA data01) {
            this.HEXADECIMAL = HEXADECIMAL;
            this.data01 = data01;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataResponse", Namespace="http://Kmieai/DMDI/data", Order=0)]
        public KIN_InvoiceEDI.KIN_Service.getDataResponseBody Body;
        
        public getDataResponse() {
        }
        
        public getDataResponse(KIN_InvoiceEDI.KIN_Service.getDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kmieai/DMDI/data")]
    public partial class getDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KIN_InvoiceEDI.KIN_Service.O_DATA getDataResult;
        
        public getDataResponseBody() {
        }
        
        public getDataResponseBody(KIN_InvoiceEDI.KIN_Service.O_DATA getDataResult) {
            this.getDataResult = getDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : KIN_InvoiceEDI.KIN_Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<KIN_InvoiceEDI.KIN_Service.ServiceSoap>, KIN_InvoiceEDI.KIN_Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KIN_InvoiceEDI.KIN_Service.getDataResponse KIN_InvoiceEDI.KIN_Service.ServiceSoap.getData(KIN_InvoiceEDI.KIN_Service.getDataRequest request) {
            return base.Channel.getData(request);
        }
        
        public KIN_InvoiceEDI.KIN_Service.O_DATA getData(string HEXADECIMAL, KIN_InvoiceEDI.KIN_Service.INUPUT_DATA data01) {
            KIN_InvoiceEDI.KIN_Service.getDataRequest inValue = new KIN_InvoiceEDI.KIN_Service.getDataRequest();
            inValue.Body = new KIN_InvoiceEDI.KIN_Service.getDataRequestBody();
            inValue.Body.HEXADECIMAL = HEXADECIMAL;
            inValue.Body.data01 = data01;
            KIN_InvoiceEDI.KIN_Service.getDataResponse retVal = ((KIN_InvoiceEDI.KIN_Service.ServiceSoap)(this)).getData(inValue);
            return retVal.Body.getDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KIN_InvoiceEDI.KIN_Service.getDataResponse> KIN_InvoiceEDI.KIN_Service.ServiceSoap.getDataAsync(KIN_InvoiceEDI.KIN_Service.getDataRequest request) {
            return base.Channel.getDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KIN_InvoiceEDI.KIN_Service.getDataResponse> getDataAsync(string HEXADECIMAL, KIN_InvoiceEDI.KIN_Service.INUPUT_DATA data01) {
            KIN_InvoiceEDI.KIN_Service.getDataRequest inValue = new KIN_InvoiceEDI.KIN_Service.getDataRequest();
            inValue.Body = new KIN_InvoiceEDI.KIN_Service.getDataRequestBody();
            inValue.Body.HEXADECIMAL = HEXADECIMAL;
            inValue.Body.data01 = data01;
            return ((KIN_InvoiceEDI.KIN_Service.ServiceSoap)(this)).getDataAsync(inValue);
        }
    }
}
